name: ivmjwt
version: 0.1.5
description: >-
  This library is designed to work with JWT (RFC7519).
  The primerary purpose is issue and verify tokens signed RSA (SHA-256)
homepage: https://github.com/dasiyes/ivmjwt

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.0
  json_annotation: ^3.0.0
  uuid_type: ^1.1.1
  meta: ^1.2.4
  ivmjv: ^0.1.6

dev_dependencies:
  test: ^1.5.0
  test_process: ^1.0.5
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  build_test: ^1.3.0
  pedantic: ^1.9.2
