name: ivmjwt
version: 0.0.1
description: >-
  This library is designed to work with JWT (RFC7519).
  The primerary purpose is verify token signed with RS256
homepage: http://ivmanto.dev/ivmjwt

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.0
  json_annotation: ^3.0.0

dev_dependencies:
  test: ^1.5.0
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  build_test: ^1.3.0
